---
- name: "Check whether the node exporter has already been installed"
  stat:
    path: "/usr/local/bin/redis_exporter"
    checksum_algorithm: "{{ redis_exporter_checksum_algorithm }}"
  register: "bin"

- name: "Fetch the archive from GitHub"
  get_url:
    url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-{{ redis_exporter_arch }}.tar.gz"
    dest: "/tmp/redis_exporter-{{ redis_exporter_version }}.linux-{{ redis_exporter_arch }}.tar.gz"
    checksum: "{{ redis_exporter_checksum_algorithm }}:{{ redis_exporter_checksum_archive }}"
  when: bin.stat.exists == False or
        bin.stat.checksum != redis_exporter_checksum_binary

- name: "Unpack the archive in /tmp"
  unarchive:
    remote_src: true
    src: "/tmp/redis_exporter-{{ redis_exporter_version }}.linux-{{ redis_exporter_arch }}.tar.gz"
    dest: "/tmp"
  when: bin.stat.exists == False or
        bin.stat.checksum != redis_exporter_checksum_binary

- name: "Move redis_exporter to the /usr/local/bin/redis_exporter"
  copy:
    remote_src: true
    src: "/tmp/redis_exporter"
    dest: "/usr/local/bin/redis_exporter"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=rwx"
  when: bin.stat.exists == False or
        bin.stat.checksum != redis_exporter_checksum_binary
  notify: "restart redis_exporter"

- name: "Clean the /tmp/ dir up"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/tmp/redis_exporter-{{ redis_exporter_version }}.linux-{{ redis_exporter_arch }}.tar.gz"
    - "/tmp/redis_exporter-0.14.0.linux-{{ redis_exporter_arch }}/"
  when: bin.stat.exists == False or
        bin.stat.checksum != redis_exporter_checksum_binary
